export const SERVICE_COMPANIES = [
  { name: "Partyverse", logo: "partyverse.png" },
  { name: "Kuda Bank", logo: "kuda.png" },
  { name: "Wema Bank", logo: "wema.png" },
  { name: "Flutterwave", logo: "flutterwave.png" },
  { name: "Grey", logo: "grey.png" },
  { name: "Bayse.Markets", logo: "bayse.png" },
  { name: "Paga", logo: "paga.png" },
  { name: "Cowrywise", logo: "cowrywise.png" },
  { name: "Risevest", logo: "rise.png" },
  { name: "Selar", logo: "selar.png" },
  { name: "Chowdeck", logo: "chowdeck.png" },
  { name: "Providus Bank", logo: "providus.png" },
  { name: "Raenest", logo: "raenest.png" },
  { name: "Paystack", logo: "paystack.png" },
  { name: "Moniepoint", logo: "moniepoint.png" },
  { name: "Carbon", logo: "carbon.png" },
  { name: "Ladda", logo: "ladda.png" },
  { name: "Mono", logo: "mono.png" },
  { name: "Remita", logo: "remita.png" },
  { name: "Bumpa", logo: "bumpa.png" },
  { name: "PaidHR", logo: "paidhr.png" },
  { name: "Brass", logo: "brass.png" },
  { name: "SeamlessHR", logo: "seamlesshr.png" },
  { name: "Mainstack", logo: "mainstack.png" },
] as const;

export const SERVICE_COMPANY_NAMES = SERVICE_COMPANIES.map(
  (company) => company.name,
);
