name: Deploy Landing

on:
  push:
    branches:
      - main
    tags:
      - 'v2*'

jobs:
  deploy-landing:
    name: Deploy Landing
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            ./deploy.sh landing ${{ github.ref_name }}
          else
            ./deploy.sh landing
          fi
        working-directory: /home/ghrunner/swift-agents-prod
